3 ➡️ 4
ignitionrobotics/ign-common pull request #185
Opened 2021-03-12 06:38 UTC by chapulina

# ➡️ Forward port

Port `ign-common3` to `main`

Branch comparison: https://github.com/ignitionrobotics/ign-common/compare/main...ign-common

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

2021-03-12 07:45 UTC, ahcorde requested changes

2021-03-12 07:45 UTC, ahcorde commented on tutorials/profiler.md
> +To start, download the [profiler.cc](https://github.com/ignitionrobotics/ign-common/raw/ign-common3/examples/profiler.cc) example.
```suggestion
To start, download the [profiler.cc](https://github.com/ignitionrobotics/ign-common/raw/main/examples/profiler.cc) example.
```

2021-03-15 20:51 UTC, chapulina commented on tutorials/profiler.md
> +To start, download the [profiler.cc](https://github.com/ignitionrobotics/ign-common/raw/ign-common3/examples/profiler.cc) example.
Fixed

2021-03-18 02:26 UTC, chapulina commented
I don't know why the actions CI is not being triggered. Closing and reopening to nudge it.

2021-03-18 02:27 UTC, chapulina commented
It looks ok now :grimacing:

2021-03-18 15:03 UTC, adlarkin commented
It looks like this forward port is missing commit https://github.com/ignitionrobotics/ign-common/commit/798f8384747975abb3c36d0ee5f831a747070f41. Can we add it in?

2021-03-18 16:53 UTC, mjcarroll commented
> It looks like this forward port is missing commit 798f838. Can we add it in?

I would prefer to forward port this one separately, if that's okay.

2021-03-19 01:32 UTC, chapulina commented
All :green_circle:

2021-03-19 02:31 UTC, adlarkin approved these changes

2021-03-19 02:34 UTC, merged