Improved Windows support
ignitionrobotics/ign-common pull request #197
Opened 2021-04-09 08:42 UTC by ahcorde

Signed-off-by: ahcorde <ahcorde@gmail.com>

# :factory_worker:  Improvement

## Summary

Improved Windows support. This PR is required here https://github.com/ignitionrobotics/ign-fuel-tools/pull/178

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-04-09 08:58 UTC, ahcorde commented
There is an issue removing a TMP_*.mp4 file in one of tests. This is not making the test to fail but I think we can open an issue. Probably this is because the file is not closed.

2021-04-09 14:11 UTC, mjcarroll requested changes
Can we add a test for the new functionality?

2021-04-09 14:11 UTC, mjcarroll commented on include/ignition/common/Util.hh
> +      // Disable warning C4307
Suggestion in https://github.com/ignitionrobotics/ign-common/pull/198

2021-04-09 14:32 UTC, mjcarroll commented on include/ignition/common/Util.hh
> +      // Disable warning C4307
#198 came back clean, so I merged it here.

2021-04-12 08:49 UTC, ahcorde commented
> Can we add a test for the new functionality?

@mjcarroll, should we make this function a method (public or private)?

2021-04-12 20:49 UTC, mjcarroll approved these changes

2021-04-12 20:49 UTC, mjcarroll commented
> @mjcarroll, should we make this function a method (public or private)?

We talked offline, this doesn't need to be a public method as it is just fixing tests.  Codecov drop is because of Linux vs Windows execution paths.

2021-04-12 20:50 UTC, merged