Add function to convert single channel image data to RGB image
ignitionrobotics/ign-common pull request #205
Opened 2021-04-23 20:56 UTC by iche033

# 🎉 New feature

## Summary
Added a generic helper function for converting single channel image data, e.g. thermal and depth images, to an RGB image. This is intended to be used for visualization. Optional arguments can be specified to tweak the visualization. 

## Test it

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-04-23 22:44 UTC, chapulina commented on graphics/include/ignition/common/Image.hh
> +            if (v < min && !std::isinf(v))
Windows is not happy about these `isinf` calls with `uint8_t`:

<details><summary>Compiler error</summary>
<p>

```
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_math.h(409): error C2668: 'fpclassify': ambiguous call to overloaded function
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_math.h(300): note: could be 'int fpclassify(long double) noexcept'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_math.h(295): note: or       'int fpclassify(double) noexcept'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_math.h(290): note: or       'int fpclassify(float) noexcept'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_math.h(409): note: while trying to match the argument list '(_Ty)'
        with
        [
            _Ty=uint8_t
        ]
C:\Jenkins\workspace\ignition_common-ci-pr_any-windows7-amd64\ws\ign-common\graphics\include\ignition/common/Image.hh(226): note: see reference to function template instantiation 'bool isinf<T>(_Ty) noexcept' being compiled
        with
        [
            T=uint8_t,
            _Ty=uint8_t
        ]
C:\Jenkins\workspace\ignition_common-ci-pr_any-windows7-amd64\ws\ign-common\graphics\src\Image_TEST.cc(351): note: see reference to function template instantiation 'void ignition::common::Image::ConvertToRGBImage<uint8_t>(const void *,unsigned int,unsigned int,ignition::common::Image &,T,T,bool)' being compiled
        with
        [
            T=uint8_t
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xstring(1739): note: see reference to class template instantiation 'std::basic_string_view<char,std::char_traits<char>>' being compiled
```

</p>
</details>

2021-04-26 07:11 UTC, ahcorde requested changes

2021-04-26 07:11 UTC, ahcorde commented on graphics/include/ignition/common/Image.hh
> +      /// \param[in] _min Maximum value to be used when normalizing the input
```suggestion
      /// \param[in] _max Maximum value to be used when normalizing the input
```

2021-04-26 07:11 UTC, ahcorde commented on graphics/include/ignition/common/Image.hh
> +      /// \param[in[ _flip True to flip the values after normalization, i.e.
```suggestion
      /// \param[in] _flip True to flip the values after normalization, i.e.
```

2021-04-26 18:29 UTC, iche033 commented on graphics/include/ignition/common/Image.hh
> +      /// \param[in[ _flip True to flip the values after normalization, i.e.
fe9fffe6e07e66f4b28d96632ed02571e8591ddc

2021-04-26 18:29 UTC, iche033 commented on graphics/include/ignition/common/Image.hh
> +      /// \param[in] _min Maximum value to be used when normalizing the input
fe9fffe6e07e66f4b28d96632ed02571e8591ddc

2021-04-26 18:46 UTC, ahcorde approved these changes

2021-04-26 19:39 UTC, mjcarroll reviewed
An approach to remove `new/delete` as well as the raw pointers: https://github.com/ignitionrobotics/ign-common/pull/206

2021-04-27 12:25 UTC, mjcarroll approved these changes
LGTM

2021-04-27 12:38 UTC, merged