Added method to remove meshes from the MeshManager
ignitionrobotics/ign-common pull request #222
Opened 2021-05-14 21:24 UTC by ahcorde

Signed-off-by: ahcorde <ahcorde@gmail.com>
# 🎉 New feature

Closes https://github.com/ignitionrobotics/ign-common/issues/37

## Summary

This PR adds and API to remove meshes from the MeshManager. This PR is also related with memory leak https://github.com/ignitionrobotics/ign-gui/issues/208

For now it's a draft PR this may require some more changes.

## Test it

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-05-17 12:33 UTC, mjcarroll requested changes
Looks good overall, I believe that the ABI checker is a false alarm?

2021-05-17 12:33 UTC, mjcarroll commented on graphics/src/MeshManager.cc
> +  std::cerr << "Trying to remove " << _name << '\n';
Remove debug print

2021-05-17 12:33 UTC, mjcarroll commented on graphics/src/MeshManager.cc
> +      std::cerr << "Mesh founded" << '\n';
debug print

2021-05-17 12:33 UTC, mjcarroll commented on graphics/src/MeshManager.cc
> +    std::cerr << "Calling Mesh destructor" << '\n';
debug print

2021-05-17 12:33 UTC, mjcarroll commented on graphics/src/MeshManager.cc
> +  bool founded = false;
Two variables `found` vs `founded` is a bit confusing.

2021-05-17 12:33 UTC, mjcarroll commented on graphics/include/ignition/common/MeshManager.hh
> +      public: void RemoveMesh(const std::string &_name);
Add docs

2021-05-18 19:51 UTC, ahcorde commented
@mjcarroll 

I have been thinking that maybe we should not allow to remove some special meshes. Such the initial ones:

 - axis_head
 - axis_shaft
 - body_cg
 - joint_anchor
 - selection_tube
 - unit_box
 - unit_camera
 - unit_cone
 - unit_cylinder
 - unit_plane
 - unit_sphere

Where do you think is the best place to store this info ?

2021-05-20 20:08 UTC, ahcorde commented
@mjcarroll, I have more questions regarding the naming of the meshes, In general there are two types of names:

 - The predefined object and the inserted object have a short name (for example: `unit_box`, `unit_capsule`, etc.
 - When we insert a model with a mesh the name of the mesh is the full path to the mesh in your system. (for example: $HOME/.ignition/fuel/fuel.ignitionrobotics.org/googleresearch/models/threshold_dinner_plate_square_rim_white_porcelain/1/meshes/model.obj

The first kind of objects are very easy to remove but I'm not sure I'm doing the right thing with the second type. For example:

I have a mesh on ignition called `box`, this logic should return `box` or `unit_box` or any other mesh with the keyword `box`in the naming. And this is not what we are looking for. One thing that I can do to improve this is to tokenize the name of the mesh by `/`. But I'm not pretty sure that all meshes will respect `<owner>/models/<name of mesh>/<version>/meshes/<name of file>`. In particular the meshes folder.

To complicate a little bit more the issue, I'm removing this from ign-gazebo using the visual's name, but probably this name will not match with name of the mesh in many cases.

2021-09-15 00:44 UTC, chapulina commented
@ahcorde  / @mjcarroll , what's the status of this PR?

I'm not sure if this has been brought up, but we have to be careful when removing meshes because they may be reused by many models.

2021-11-08 18:57 UTC, chapulina approved these changes
LGTM. We need to be careful downstream when using these functions though. Meshes are often reused and removing one of them may have unintended consequences.

2021-11-09 05:39 UTC, merged

2022-01-25 01:01 UTC, osrf-triage commented
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-01-24-citadel-edifice-fortress/1241/1