Suggestion to #227: More data race fixes
ignitionrobotics/ign-common pull request #237
Opened 2021-08-06 15:53 UTC by azeey

# 🦟 Bug fix

## Summary
I ran the `PERFORMANCE_logging` test under TSAN and found more data races. One deals with `std::localtime`, which apparently is not thread-safe as it returns a pointer to an internal static object. The others deal with the fact that the `Buffer` class has a `std::string` member inherited from `std::stringbuf` and it (the string) also needs synchronization.

I put the mutex as a member in `Buffer` since it's needed in two functions. This means that each console stream (i.e. ignmsg, ignwarn, etc) gets its own mutex. It turns out we don't really need to synchronize on the `stdout` or `stderr` 
According to https://timsong-cpp.github.io/cppwp/n3337/iostream.objects#overview-4, accessing `stdout` or `stderr` from multiple threads should not cause a data race, so we don't need a global mutex for them. It does say we should synchronize if we want to avoid interleaved messages, but since we write the `prefixString` and the main message separately, we wouldn't be able to avoid interleaved messages even with global synchronization.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-08-09 10:46 UTC, ahcorde requested changes

2021-08-09 10:46 UTC, ahcorde commented on include/ignition/common/Console.hh
> +
```suggestion
```

2021-08-09 20:34 UTC, mjcarroll commented on include/ignition/common/Console.hh
> +                   public: virtual std::streamsize xsputn(
I believe that `sync` below also needs to be marked override to make macos happy.

2021-08-10 10:46 UTC, ahcorde requested changes

2021-08-10 10:46 UTC, ahcorde commented on include/ignition/common/Console.hh
> +                   /// \brief Mutex to syncronize writes to the string buffer
```suggestion
                   /// \brief Mutex to synchronize writes to the string buffer
```

2021-08-10 13:35 UTC, mjcarroll approved these changes

2021-08-10 13:59 UTC, ahcorde approved these changes

2021-08-10 14:12 UTC, merged